### ISSUE TITLE
No values shown in variabels.

### ISSUE THREAD

**Issue by PC-chassisdyno** [GTO2013/EMUSerial#2]
Is it enough to connect TX pin 2 on EMU Exp port and GND or also connect RX for handshake ? Cant see any handshake in the code though. Have made a new struct file on my fw 1.207 in EMU. Have also tested with Mega 2560 to run debug on second serial but no values shown.

**Comment by GTO2013** [comment]
Hi,
you are using a chip that converts the RS232 voltage levels to TTL correct? Serial stream is also enabled in the emu? TX on the emu is also connected to RX on the arduino side? When I tested this I also had RX connected I think.
Nice Escort by the way!

**Comment by PC-chassisdyno** [comment]
Thanks yes thats a grp-4 with 2 liters pinto. I have connected the Emu tx directly to arduino mega rx. Wrong ?

**Comment by PC-chassisdyno** [comment]
Yes serialstream is set to EMU serial. Use to have it on Datalogger then i have a EDL-1 logger.

**Comment by GTO2013** [comment]
The EMU sends on RS232 (15V) voltage levels, you need a converter chip like an e.g. MAX3232CPE that converts it to 5V TTL. If it still doesnt work afterwards its possible that the pins got damaged on the Arduino Mega

**Comment by PC-chassisdyno** [comment]
Yes probably toasted i/p now. I have ordered a RS-232/TTL and will test tomorow.
 I have built a gearchange unit of a standalone AtMega 328 and its where signal from ECU will be used for speed and which gear. Its allso a loadcell conected to gearbox with cuts the ignition when upgear. Tanks for all help.

**Comment by GTO2013** [comment]
Nice project. Let me know if you got it working!

**Comment by PC-chassisdyno** [comment]
Now its working fine. But to bad i cant use my EDL-1 cause not same protocol.

**Comment by GTO2013** [comment]
Yeah its a shame they use a different protocol...
