### ISSUE TITLE
Arduino nano

### ISSUE THREAD

**Issue by TCOPC** [GTO2013/EMUSerial#4]
Hey,

I want to use this project but I can't upload it to my Arduino nano.
Can someone help me?

Kind regards,
Thomas

**Comment by GTO2013** [comment]
The Arduino Nano only has one Serial port, which might not work correctly if you already have the TTL converter attached to it. It should work if you disconnect the TTL converter, upload the sketch and then reconnect it. For debugging you can also use SoftwareSerial :)

**Comment by TCOPC** [comment]
Thanks for the quick response!
I can't even upload the sketch to the Arduino but maybe it's because of that the nano only has 1 serial port.
I can try to find another Arduino or also use a ESP32

**Comment by GTO2013** [comment]
The USB port is attached to the RX TX lines, if you disconnect any hardware from those pins you should be able to upload it. You then have to reconnect it. So yeah, its probably better to use another Arduino.

**Comment by designer2k2** [comment]
would it be possible to use SoftwareSerial for EMUSerial?

**Comment by GTO2013** [comment]
I intentionally used the Stream interface to make this possible, but I never tested it. If you configure it for 8 Databits 1 Stopbit it should work. Let me know if you have success!

**Comment by GTO2013** [comment]
I will close this for now, if you have future issues let me know!
