### ISSUE TITLE
Serial1 - cant be Compiled (+:Multiple devices on one port?)

### ISSUE THREAD

**Issue by kvnbdn** [GTO2013/EMUSerial#5]
At first, great work!

When i try to compile the example, it gives the error "couldnt find that function" (serial1)
Tried it, without connection to the emu.
Did i miss something?

Second, bit off-topic - but i am a totally noob:
Is it possible to connect the ecu masters-bluetooth module to the emu and connect the arduino via bluetooth - or maybe connect between the emu and the bt module?

Thanks !

**Comment by GTO2013** [comment]
Which Arduino are you using? The example is for an ESP32, which has two Serial ports. If you have an Arduino with one Serial port you can try to remove the Debug Port and test the first Serial port. You are using an RS232 to TTL converter right?
I dont have any experience with the bluetooth module, sorry!

**Comment by kvnbdn** [comment]
For bench testing an Arduino Mega 2560. Converter just arrived today, couldnt test it so far - however i  didnt connect it to the emu so far because when i try to compile it, just gives me the error.

Second:
Ecu master support says: 
"More than one device can be connected as long as all devices are only receiving from the transmit terminal and no serial handshake is required."
Not quite sure how to wire this :D 
​Sorry for my bad knowledge, just started two weeks ago, working into this stuff.

**Comment by kvnbdn** [comment]
Found the first Problem! Got a problem with the pin-numbers.

// Serial1.begin(19200, SERIAL_8N1, **19, 21**); //EMU Serial setup, 8 Data Bits 1 Stopbit, RX Pin, TX Pin

On the Mega 2560 Serial1 is 18 and 19 BUT - think this is just not needed.
Changed that into just " Serial1.begin(19200, SERIAL_8N1); " and it will compile with no problem. It was just overdefined?

**Comment by GTO2013** [comment]
I dont have much experience with the Mega, but yeah that should work now!

**Comment by kvnbdn** [comment]
Little late but i am back with good news!
At first, connection to the EMU works just fine on the MEGA (with adjusted code).
Second, multiple connection to devices, shouldnt be a problem either. Just connect between the two devices, an just let it recieve.
Couldnt try it so far, cuz didnt have time for.
Gonna close this one, thanks and may this help some one!
Cheers
